---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neutrino-gateway
  labels:
    app: neutrino-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neutrino-gateway
  labels:
    app: neutrino-gateway
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neutrino-gateway
  labels:
    app: neutrino-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neutrino-gateway
subjects:
- kind: ServiceAccount
  name: neutrino-gateway
  namespace: default
