apiVersion: v1
kind: Service
metadata:
  name: neutrino-gateway
  labels:
    app: neutrino-gateway
spec:
  type: LoadBalancer
  selector:
    app: neutrino-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
